### PR TITLE
Playhead text customization

### PR DESCRIPTION
**Pull request by amber-huo**
#507 

This adds two options for customizing playhead text:
- background color
- padding around the text

### CODE REVIEW

**Comment by chrisn** [comment]
Thank you! With the padding option, could this apply to both the left and right of the text, at the moment it looks to be only on the right.  What do you think?

Another thing I would suggest is rename the `playheadBkgrdColor` as `playheadBackgroudColor`, so it's not abbreviated.

**Comment by amber-huo** [comment]
> Thank you! With the padding option, could this apply to both the left and right of the text, at the moment it looks to be only on the right. What do you think?
> 
> Another thing I would suggest is rename the `playheadBkgrdColor` as `playheadBackgroudColor`, so it's not abbreviated.

Sure, took both your suggestions.

**Comment by chrisn** [comment]
Thank you! I'm just doing some testing. There are a couple of other minor things I'd like to consider. One is, when the playhead is close to the right-hand edge of the view, the playhead text moves to the left of the playhead, so ideally this would also take into account the padding. The other is that there's a really small gap between the playhead and the padding, would it look better if we could remove this?

**Comment by amber-huo** [comment]
Ok, I adjusted for padding when the text moves to the left, and removed the gap. The padding has a default of 2 so the text should look the same as before when there is no custom background or padding set.

**Comment by chrisn** [comment]
This looks great, thank you!

**Comment by chrisn** [comment]
The only final things are to add some documentation and a few really minor nitpicks on the code. Would you prefer if I do those, or should I suggest changes?

**Comment by amber-huo** [comment]
I'm cool if you go ahead and do those! Thanks.

**Pull request merged**
