### PR TITLE
Move to ES Modules

### PR DESCRIPTION
**Pull request by oncletom**
I'm integrating Peaks.js into a Vue application (yay!), and I fancied running an extra mile to migrate the codebase to EcmaScript Modules.

- [x] move from RequireJS to ES Modules
- [x] replace Browserify with Rollup (spits out multiple bundles, including ESM ones!)
- [x] hand pick `Konva` components, as it might end up in a smaller bundle
- [x] tests pass
- [ ] `Peaks.init()` returns a Promise (but well, it changes the API so 🤷 ❓)

Maybe there are a few things to check over — the demos seem to work as they used to.
It was more or less easy to migrate, as the codebase was pretty much in line with what became ES6 classes!

Let me know if you'd like more details, or clarifications to make up your mind on the mergeability of this proposal.

### CODE REVIEW

**Comment by oncletom** [comment]
Oh, I realised in #310 there is already an ongoing effort to do such a thing 🤦

**Comment by chrisn** [comment]
Yes, I have a local branch where it's basically complete. Let me compare with your PR. I was also holding off merging for a while as we have some other changes in progress from other contributors.

**Comment by jdelStrother** [comment]
> I was also holding off merging for a while as we have some other changes in progress from other contributors.

If I'm one of those contributors, don't hold off switching to ES modules for my sake. I suspect that the segment-dragging thing is going to take a while to hammer out, and I'm happy to reapply my changes to an ES version.

(Obviously other contributors may feel differently 😛 )

**Comment by chrisn** [comment]
@jdelStrother Yes, I was thinking about your create segments via dragging change.

**Comment by chrisn** [comment]
Thank you so much @oncletom. I'll close this as I'd already got this working separately. I have credited you in the changelog.

**Pull request closed without merging**
