### PR TITLE
TypeScript Definitions

### PR DESCRIPTION
**Pull request by evanlouie**
- Added `peaks.js.d.ts` TypeScript definitions file

https://github.com/bbc/peaks.js/issues/217

### CODE REVIEW

**Comment by chrisn** [comment]
Amazing, thank you! I'll take a closer look and then merge.

**Comment by chrisn** [comment]
I'm reading the TypeScript documentation for [publishing declaration files](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html). Do we need to add a `types` entry to package.json? Or publish to the types npm organization, maybe?

**Comment by evanlouie** [comment]
Apologies for that, forgot to add the entry to `package.json`

**Comment by chrisn** [comment]
No problem, I wasn't sure what the right approach is. LGTM, will merge.

**Comment by chrisn** [comment]
@evanlouie Many thanks for your contribution, published as v0.9.13.

**Pull request merged**
