### PR TITLE
Rely on player.currentTime for syncing the playhead animation

### PR DESCRIPTION
**Pull request by jdelStrother**
An alternative approach to #206

### CODE REVIEW

**Comment by jdelStrother** [comment]
I wonder if the pixelsPerSecond limit (https://github.com/bbc/peaks.js/blob/5855ae58f7645252941de957fda9f80df4923159/src/main/views/playhead-layer.js#L57) should be lowered.  On the demo page sample, the overview waveform doesn't have animations enabled, and the playhead usually jumps 2 pixels at a time.

**Comment by jdelStrother** [comment]
👍

**Comment by chrisn** [comment]
I made a change to ensure that the playhead time label updates when zoomed out to levels where the `Konva.Animation` isn't used. Updates are driven by the media element's `timeupdate` event, so occur much less frequently than using the animation loop. I think this is OK, and better than only updating the label when the playhead moves pixel position, which can be only every few seconds, depending on zoom level. If you're happy with this, I think we can merge.

**Comment by jdelStrother** [comment]
Thanks, looks good to me

**Pull request merged**
