### PR TITLE
Overview highlight offset

### PR DESCRIPTION
**Pull request by jodonnell**

### CODE REVIEW

**Comment by chrisn** [comment]
Thanks! Perhaps we should also add code to prevent the height from going negative?

**Comment by jodonnell** [comment]
well we could do 
```y: Math.max(this._options.overviewHighlightOffset, 0),```
although going negative won't harm anything because it will draw outside the canvas which won't get rendered.

Or were you thinking like at startup time around where the deprecation warnings are it would throw an error?

**Comment by chrisn** [comment]
I was more thinking of possibility that Konva may error, but if that doesn't happen we're fine. I don't think we need a warning.

**Comment by jodonnell** [comment]
ahh dang, i didn't update the README.

should I make one more PR with the Readme updated?

And if i want to create a release after it suggests I push right to master but i really doubt i have permissions to do that, so I could create a PR were I update the change log and bump the version.

**Comment by chrisn** [comment]
Don't worry, I'll do the README and the release. Thanks for contributing!

**Comment by jodonnell** [comment]
Okay great, thanks for the help.

**Comment by chrisn** [comment]
I have just pushed the v0.14.3 release, it should be available in npm shortly.

**Comment by chrisn** [comment]
So we do need to add some validation, if I make the offset too large we get this error from Konva:

> DOMException: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-7.5) is negative.

**Comment by jodonnell** [comment]
okay i'll take a look

**Comment by jodonnell** [comment]
okay this happens when the offset is over half the height.

i'm not sure how to implement this though, because where i would think to put this validation, the same place i put the depreciation warning won't work i don't think.

the height is often set via css so i don't think i'd have access to the true height of the canvas.

where do you think putting this would make sense?

**Comment by chrisn** [comment]
Another consideration is dynamically resizing of the waveform view (see #224). What I'd suggest is not throwing an error, but instead applying some minimum values to `y` and `height` in `_createHighlightRect`, which override the user's option setting.

**Comment by jodonnell** [comment]
good thinking 👍 , will have pr up soon

**Comment by jodonnell** [comment]
https://github.com/bbc/peaks.js/pull/289

**Pull request merged**
